[package]
name = "qmc"
version = "0.1.0"
authors = []
build = "build.rs"

[lib]
name = "qmc"
crate-type = ["dylib", "rlib"]

[dependencies]
docopt = "0.6.81"
libc = "*"
modulo = "0.1.1"
num = "0.1.34"
rand = "0.3"
rustc-serialize = "0.3.19"
