#!/usr/bin/env python
import base64, os
import numpy as np
import numpy.random as npr
import matplotlib.pyplot as plt
from numpy import sqrt
from utils import *

seed = base64.b16encode(os.urandom(20)).decode("ascii")
print("seed: {0}".format(seed))
data = run("qmc", **{
    "seed": seed,
    "population": 10000,
    "num_steps": 10000,
    "print_interval": 10,
    "dt": 0.001,
    "branch_interval": 10,
})
fig, ax = plt.subplots()
err = sqrt((data["stats.sq_energy"] - data["stats.energy"] ** 2)
           / data["stats.weight"])
ax.fill_between(
    data["time"],
    data["stats.energy"] - err,
    data["stats.energy"] + err,
    alpha=0.8,
    linewidth=0)
ax.plot(
    data["time"],
    data["growth_energy"],
    alpha=0.8,
    color="red")
ax.plot(
    data["time"],
    data["stats.sq_x"],
    alpha=0.8,
    color="green")
plt.show()
